//! Validates that a directory is a conformant OKF bundle — generated by
//! `okf-generator` or hand-edited — per the checks described in the
//! project specification's Validation section:
//!
//! - the bundle has a root `index.md` (every other check below assumes
//!   one exists to anchor reachability against)
//! - every concept file has a valid YAML frontmatter block with the
//!   mandatory `type` field
//! - frontmatter values match expected shapes (`tags` is a list,
//!   `timestamp`/`generated.at`/`verified[].at` are RFC 3339, `stale_after`
//!   and `sources[].last_modified` are `YYYY-MM-DD` dates, `status` is one
//!   of `draft`/`stable`/`deprecated`)
//! - the OKF v0.2 trust, provenance, and lifecycle families (`generated`,
//!   `verified`, `sources`, `status`, `stale_after`), when present, match
//!   their spec shape, and actor identities (`generated.by`,
//!   `verified[].by`) follow the `<producer>/<version>` / `human:<id>` /
//!   `process:<id>` convention (a warning, not an error, since the
//!   convention is producer guidance)
//! - a bundle-root `index.md`'s optional `okf_version` declaration is a
//!   well-formed `<major>.<minor>` string, and no other `index.md` carries
//!   frontmatter at all
//! - no duplicate concept identity: neither two files colliding on path
//!   (case-insensitively, since paths become filesystem entries that may
//!   not distinguish case) nor two files independently describing the
//!   same source location (`resource`)
//! - frontmatter `relationships` targets (`calls`/`called_by`/`imports`/
//!   `member_of`/...) resolve to concepts that exist in the bundle, same
//!   as markdown links (external targets, prefixed `external/`, are
//!   exempt by convention — see `okf-generator`)
//! - `calls`/`called_by` are symmetric bundle-wide: a `Calls` edge with no
//!   matching reverse `CalledBy` (or vice versa) is flagged — the only
//!   relationship pair this applies to, since it's the only one
//!   `okf-analyzer` ever emits as two sides of the same edge
//! - markdown links between concepts resolve to files that exist in the
//!   bundle (no dangling references), and a file linking to the same
//!   target more than once is flagged as redundant
//! - every concept is reachable from `index.md` (no orphaned files)

use anyhow::{Context, Result};
use std::collections::{HashMap, HashSet, VecDeque};
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Severity {
    Error,
    Warning,
}

#[derive(Debug, Clone)]
pub struct ValidationIssue {
    pub severity: Severity,
    /// Path relative to the bundle root.
    pub file: String,
    pub message: String,
}

#[derive(Debug, Default)]
pub struct ValidationReport {
    pub issues: Vec<ValidationIssue>,
}

impl ValidationReport {
    pub fn has_errors(&self) -> bool {
        self.issues.iter().any(|i| i.severity == Severity::Error)
    }
}

struct ScannedFile {
    /// Relative path, `/`-separated, including `.md`.
    relative: String,
    content: String,
}

/// Walks `bundle_dir` and runs every validation check against it.
pub fn validate_bundle(bundle_dir: &Path) -> Result<ValidationReport> {
    let mut files = Vec::new();
    for entry in walkdir::WalkDir::new(bundle_dir) {
        let entry = entry.context("failed to walk bundle directory")?;
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("md") {
            continue;
        }
        let relative = path
            .strip_prefix(bundle_dir)
            .unwrap_or(path)
            .to_string_lossy()
            .replace('\\', "/");
        // Normalize CRLF to LF before any frontmatter parsing: files
        // edited or checked out on Windows (or with `core.autocrlf=true`)
        // are otherwise valid OKF content that the `"---\n"` delimiter
        // match would reject wholesale as "missing frontmatter".
        let content = fs::read_to_string(path)
            .with_context(|| format!("failed to read {relative}"))?
            .replace("\r\n", "\n");
        files.push(ScannedFile { relative, content });
    }
    files.sort_by(|a, b| a.relative.cmp(&b.relative));

    let mut report = ValidationReport::default();
    let known_paths: HashSet<&str> = files.iter().map(|f| f.relative.as_str()).collect();

    check_required_index(&files, &mut report);
    check_frontmatter(&files, &mut report);
    check_index_frontmatter(&files, &mut report);
    check_duplicate_ids(&files, &mut report);
    check_duplicate_resources(&files, &mut report);
    check_relationship_targets(&files, &known_paths, &mut report);
    check_relationship_symmetry(&files, &known_paths, &mut report);
    check_relationship_provenance(&files, &mut report);
    let links = check_links_and_collect(&files, &known_paths, &mut report);
    check_reachability(&files, &links, &mut report);

    Ok(report)
}

fn is_index(relative: &str) -> bool {
    relative == "index.md" || relative.ends_with("/index.md")
}

/// The bundle's root `index.md` is the anchor every other structural
/// check (reachability, in particular) assumes exists. Without this
/// check, a bundle missing it entirely degrades silently into every
/// single concept being reported as "orphaned" one at a time, instead of
/// one clear error naming the actual root cause.
fn check_required_index(files: &[ScannedFile], report: &mut ValidationReport) {
    if !files.iter().any(|f| f.relative == "index.md") {
        report.issues.push(ValidationIssue {
            severity: Severity::Error,
            file: "index.md".to_string(),
            message: "missing required root `index.md`".to_string(),
        });
    }
}

fn split_frontmatter(content: &str) -> Option<(&str, &str)> {
    let rest = content.strip_prefix("---\n")?;
    let end = rest.find("\n---\n")?;
    Some((&rest[..end], &rest[end + 5..]))
}

fn check_frontmatter(files: &[ScannedFile], report: &mut ValidationReport) {
    for file in files {
        if is_index(&file.relative) {
            continue;
        }
        let Some((yaml, _body)) = split_frontmatter(&file.content) else {
            report.issues.push(ValidationIssue {
                severity: Severity::Error,
                file: file.relative.clone(),
                message: "missing or malformed YAML frontmatter (expected a `---` delimited block)"
                    .to_string(),
            });
            continue;
        };

        let value: serde_yaml::Value = match serde_yaml::from_str(yaml) {
            Ok(v) => v,
            Err(e) => {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: file.relative.clone(),
                    message: format!("invalid YAML frontmatter: {e}"),
                });
                continue;
            }
        };

        let Some(mapping) = value.as_mapping() else {
            report.issues.push(ValidationIssue {
                severity: Severity::Error,
                file: file.relative.clone(),
                message: "frontmatter must be a YAML mapping".to_string(),
            });
            continue;
        };

        match mapping.get("type").and_then(|v| v.as_str()) {
            Some(t) if !t.trim().is_empty() => {}
            _ => report.issues.push(ValidationIssue {
                severity: Severity::Error,
                file: file.relative.clone(),
                message: "frontmatter is missing the mandatory non-empty `type` field".to_string(),
            }),
        }

        if let Some(tags) = mapping.get("tags") {
            let valid = tags
                .as_sequence()
                .map(|seq| seq.iter().all(|t| t.as_str().is_some()))
                .unwrap_or(false);
            if !valid {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: file.relative.clone(),
                    message: "`tags` must be a list of strings".to_string(),
                });
            }
        }

        if let Some(timestamp) = mapping.get("timestamp") {
            if !is_valid_datetime_value(timestamp) {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: file.relative.clone(),
                    message: "`timestamp` must be an RFC 3339 datetime".to_string(),
                });
            }
        }

        if let Some(generated) = mapping.get("generated") {
            check_generated(generated, &file.relative, report);
        }

        if let Some(verified) = mapping.get("verified") {
            check_verified(verified, &file.relative, report);
        }

        if let Some(status) = mapping.get("status") {
            if !matches!(
                status.as_str(),
                Some("draft") | Some("stable") | Some("deprecated")
            ) {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: file.relative.clone(),
                    message: "`status` must be one of `draft`, `stable`, or `deprecated`"
                        .to_string(),
                });
            }
        }

        if let Some(stale_after) = mapping.get("stale_after") {
            if !is_valid_date_value(stale_after) {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: file.relative.clone(),
                    message: "`stale_after` must be an absolute `YYYY-MM-DD` date".to_string(),
                });
            }
        }

        if let Some(sources) = mapping.get("sources") {
            check_sources(sources, &file.relative, report);
        }

        if let Some(usage_window) = mapping.get("usage_window") {
            check_usage_window(usage_window, &file.relative, report);
        }

        if mapping.get("type").and_then(|v| v.as_str()) == Some("Attested Computation") {
            let has_runtime = mapping
                .get("runtime")
                .and_then(|v| v.as_str())
                .is_some_and(|s| !s.trim().is_empty());
            if !has_runtime {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: file.relative.clone(),
                    message:
                        "an `Attested Computation` concept requires a non-empty `runtime` field"
                            .to_string(),
                });
            }
        }
    }
}

/// Renders a YAML scalar back to its string form, matching how the
/// existing `timestamp` check handles values `serde_yaml` may have parsed
/// as their own scalar type (e.g. an unquoted date) rather than a string.
fn yaml_scalar_as_string(value: &serde_yaml::Value) -> Option<String> {
    value.as_str().map(str::to_string).or_else(|| {
        serde_yaml::to_string(value)
            .ok()
            .map(|s| s.trim().to_string())
    })
}

fn is_valid_date_value(value: &serde_yaml::Value) -> bool {
    yaml_scalar_as_string(value)
        .as_deref()
        .map(|s| chrono::NaiveDate::parse_from_str(s, "%Y-%m-%d").is_ok())
        .unwrap_or(false)
}

fn is_valid_datetime_value(value: &serde_yaml::Value) -> bool {
    yaml_scalar_as_string(value)
        .as_deref()
        .map(|s| chrono::DateTime::parse_from_rfc3339(s).is_ok())
        .unwrap_or(false)
}

/// Validates the OKF v0.2 `generated` trust field (spec §5.2): a mapping
/// with a required, non-empty `by` (an actor, §7) and an optional RFC 3339
/// `at`.
fn check_generated(value: &serde_yaml::Value, file: &str, report: &mut ValidationReport) {
    let Some(mapping) = value.as_mapping() else {
        report.issues.push(ValidationIssue {
            severity: Severity::Error,
            file: file.to_string(),
            message: "`generated` must be a mapping with a `by` field".to_string(),
        });
        return;
    };
    match mapping.get("by").and_then(|v| v.as_str()) {
        Some(by) if !by.trim().is_empty() => check_actor(by, "generated.by", file, report),
        _ => report.issues.push(ValidationIssue {
            severity: Severity::Error,
            file: file.to_string(),
            message: "`generated` is missing the required non-empty `by` field".to_string(),
        }),
    }
    if let Some(at) = mapping.get("at") {
        if !is_valid_datetime_value(at) {
            report.issues.push(ValidationIssue {
                severity: Severity::Error,
                file: file.to_string(),
                message: "`generated.at` must be an RFC 3339 datetime".to_string(),
            });
        }
    }
}

/// Validates the OKF v0.2 `verified` trust field (spec §5.2): a list of
/// `{ by, at }` entries, or a single bare mapping, which consumers MUST
/// treat as a one-element list.
fn check_verified(value: &serde_yaml::Value, file: &str, report: &mut ValidationReport) {
    let owned_single;
    let entries: &[serde_yaml::Value] = match value.as_sequence() {
        Some(seq) => seq,
        None => {
            owned_single = [value.clone()];
            &owned_single
        }
    };
    for entry in entries {
        let Some(mapping) = entry.as_mapping() else {
            report.issues.push(ValidationIssue {
                severity: Severity::Error,
                file: file.to_string(),
                message: "each `verified` entry must be a mapping with a `by` field".to_string(),
            });
            continue;
        };
        match mapping.get("by").and_then(|v| v.as_str()) {
            Some(by) if !by.trim().is_empty() => check_actor(by, "verified[].by", file, report),
            _ => report.issues.push(ValidationIssue {
                severity: Severity::Error,
                file: file.to_string(),
                message: "a `verified` entry is missing the required non-empty `by` field"
                    .to_string(),
            }),
        }
        if let Some(at) = mapping.get("at") {
            if !is_valid_datetime_value(at) {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: file.to_string(),
                    message: "`verified[].at` must be an RFC 3339 datetime".to_string(),
                });
            }
        }
    }
}

/// Validates the OKF v0.2 `sources` provenance field (spec §5.1): a list of
/// entries, each requiring a non-empty `resource` and allowing the optional
/// credibility signals `last_modified`, `usage_count`, and `usage_window`.
fn check_sources(value: &serde_yaml::Value, file: &str, report: &mut ValidationReport) {
    let Some(seq) = value.as_sequence() else {
        report.issues.push(ValidationIssue {
            severity: Severity::Error,
            file: file.to_string(),
            message: "`sources` must be a list".to_string(),
        });
        return;
    };
    for entry in seq {
        let Some(mapping) = entry.as_mapping() else {
            report.issues.push(ValidationIssue {
                severity: Severity::Error,
                file: file.to_string(),
                message: "each `sources` entry must be a mapping".to_string(),
            });
            continue;
        };
        match mapping.get("resource").and_then(|v| v.as_str()) {
            Some(r) if !r.trim().is_empty() => {}
            _ => report.issues.push(ValidationIssue {
                severity: Severity::Error,
                file: file.to_string(),
                message: "a `sources` entry is missing the required non-empty `resource` field"
                    .to_string(),
            }),
        }
        if let Some(last_modified) = mapping.get("last_modified") {
            if !is_valid_date_value(last_modified) {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: file.to_string(),
                    message: "a `sources` entry's `last_modified` must be a `YYYY-MM-DD` date"
                        .to_string(),
                });
            }
        }
        if let Some(usage_count) = mapping.get("usage_count") {
            if usage_count.as_u64().is_none() {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: file.to_string(),
                    message: "a `sources` entry's `usage_count` must be a non-negative integer"
                        .to_string(),
                });
            }
        }
        if let Some(window) = mapping.get("usage_window") {
            check_usage_window(window, file, report);
        }
    }
}

fn check_usage_window(value: &serde_yaml::Value, file: &str, report: &mut ValidationReport) {
    let Some(mapping) = value.as_mapping() else {
        report.issues.push(ValidationIssue {
            severity: Severity::Error,
            file: file.to_string(),
            message: "`usage_window` must be a mapping with `from`/`to` dates".to_string(),
        });
        return;
    };
    for key in ["from", "to"] {
        match mapping.get(key) {
            Some(v) if is_valid_date_value(v) => {}
            _ => report.issues.push(ValidationIssue {
                severity: Severity::Error,
                file: file.to_string(),
                message: format!("`usage_window.{key}` must be a `YYYY-MM-DD` date"),
            }),
        }
    }
}

/// Warns (does not error) when an actor identity doesn't follow the OKF
/// convention (spec §7): `<producer>/<version>`, `human:<id>`, or
/// `process:<id>`. This is producer guidance, not a hard requirement, so a
/// mismatch is a `Warning`.
fn check_actor(actor: &str, field: &str, file: &str, report: &mut ValidationReport) {
    let looks_like_producer_version = actor
        .split_once('/')
        .is_some_and(|(producer, version)| !producer.is_empty() && !version.is_empty());
    let valid =
        actor.starts_with("human:") || actor.starts_with("process:") || looks_like_producer_version;
    if !valid {
        report.issues.push(ValidationIssue {
            severity: Severity::Warning,
            file: file.to_string(),
            message: format!(
                "`{field}` value `{actor}` doesn't follow the OKF actor convention (`<producer>/<version>`, `human:<id>`, or `process:<id>`)"
            ),
        });
    }
}

/// Validates the OKF v0.2 `okf_version` declaration (spec §12), permitted
/// only in a bundle-root `index.md`: every other `index.md` MUST NOT carry
/// frontmatter at all (spec §8).
fn check_index_frontmatter(files: &[ScannedFile], report: &mut ValidationReport) {
    for file in files {
        if !is_index(&file.relative) {
            continue;
        }
        let has_frontmatter = file.content.starts_with("---\n");
        if file.relative != "index.md" {
            if has_frontmatter {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: file.relative.clone(),
                    message: "only the bundle-root index.md may carry YAML frontmatter (an `okf_version` declaration); other index.md files must not".to_string(),
                });
            }
            continue;
        }
        if !has_frontmatter {
            continue;
        }
        let Some((yaml, _)) = split_frontmatter(&file.content) else {
            report.issues.push(ValidationIssue {
                severity: Severity::Error,
                file: file.relative.clone(),
                message: "malformed YAML frontmatter in the bundle-root index.md (expected a `---` delimited block)".to_string(),
            });
            continue;
        };
        let value: serde_yaml::Value = match serde_yaml::from_str(yaml) {
            Ok(v) => v,
            Err(e) => {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: file.relative.clone(),
                    message: format!("invalid YAML frontmatter in the bundle-root index.md: {e}"),
                });
                continue;
            }
        };
        let Some(mapping) = value.as_mapping() else {
            report.issues.push(ValidationIssue {
                severity: Severity::Error,
                file: file.relative.clone(),
                message: "the bundle-root index.md frontmatter must be a YAML mapping".to_string(),
            });
            continue;
        };
        if let Some(version) = mapping.get("okf_version") {
            // serde_yaml may parse an unquoted `okf_version: 0.2` as its own
            // numeric scalar rather than a string; round-trip it back, same
            // as every other version/date/timestamp check in this file.
            let valid = yaml_scalar_as_string(version)
                .as_deref()
                .is_some_and(is_valid_okf_version);
            if !valid {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: file.relative.clone(),
                    message: "`okf_version` must be a `<major>.<minor>` string (e.g. \"0.2\")"
                        .to_string(),
                });
            }
        }
    }
}

fn is_valid_okf_version(s: &str) -> bool {
    let Some((major, minor)) = s.split_once('.') else {
        return false;
    };
    !major.is_empty()
        && !minor.is_empty()
        && major.chars().all(|c| c.is_ascii_digit())
        && minor.chars().all(|c| c.is_ascii_digit())
}

fn check_duplicate_ids(files: &[ScannedFile], report: &mut ValidationReport) {
    let mut by_lower: HashMap<String, Vec<&str>> = HashMap::new();
    for file in files {
        by_lower
            .entry(file.relative.to_ascii_lowercase())
            .or_default()
            .push(&file.relative);
    }
    for (_, paths) in by_lower {
        if paths.len() > 1 {
            let mut sorted = paths.clone();
            sorted.sort();
            for path in &sorted {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: path.to_string(),
                    message: format!(
                        "concept id collides case-insensitively with: {}",
                        sorted
                            .iter()
                            .filter(|p| **p != *path)
                            .cloned()
                            .collect::<Vec<_>>()
                            .join(", ")
                    ),
                });
            }
        }
    }
}

/// Catches the OKF spec's other "duplicate concept identity" case:
/// `check_duplicate_ids` only catches two files that collide on *path*,
/// but a source symbol can just as easily be emitted twice under two
/// *different* paths (e.g. a stale file left behind after a rename, or a
/// hand-edited copy) — that's detected here by two concept files sharing
/// the same `resource` (source location).
///
/// A `Module` concept's `resource` is definitionally the whole file, so it
/// legitimately coincides with a member's location whenever that member is
/// the file's only top-level item (a common shape: a file containing
/// exactly one function/class/struct) — that's expected containment, not
/// a duplicate identity. So `Module` resources and non-`Module` resources
/// are checked for collisions separately: a real duplicate (two `Function`
/// files sharing a resource, or two `Module` files sharing one) is still
/// caught, but a `Module` overlapping its own sole member never is.
fn check_duplicate_resources(files: &[ScannedFile], report: &mut ValidationReport) {
    let mut by_resource: HashMap<String, Vec<(&str, bool)>> = HashMap::new();
    for file in files {
        if is_index(&file.relative) {
            continue;
        }
        let Some((yaml, _)) = split_frontmatter(&file.content) else {
            continue;
        };
        let Ok(value) = serde_yaml::from_str::<serde_yaml::Value>(yaml) else {
            continue;
        };
        let Some(mapping) = value.as_mapping() else {
            continue;
        };
        let Some(resource) = mapping.get("resource").and_then(|v| v.as_str()) else {
            continue;
        };
        let is_module = mapping
            .get("type")
            .and_then(|v| v.as_str())
            .is_some_and(|t| t.ends_with(" Module"));
        by_resource
            .entry(resource.to_string())
            .or_default()
            .push((&file.relative, is_module));
    }

    for (resource, entries) in by_resource {
        let modules: Vec<&str> = entries
            .iter()
            .filter(|(_, is_module)| *is_module)
            .map(|(path, _)| *path)
            .collect();
        let others: Vec<&str> = entries
            .iter()
            .filter(|(_, is_module)| !*is_module)
            .map(|(path, _)| *path)
            .collect();

        for paths in [modules, others] {
            if paths.len() <= 1 {
                continue;
            }
            let mut sorted = paths.clone();
            sorted.sort();
            for path in &sorted {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: path.to_string(),
                    message: format!(
                        "duplicate concept identity: `resource: {resource}` also appears in: {}",
                        sorted
                            .iter()
                            .filter(|p| **p != *path)
                            .cloned()
                            .collect::<Vec<_>>()
                            .join(", ")
                    ),
                });
            }
        }
    }
}

/// Extracts a `relationships.<kind>` sequence entry's target id, whether
/// it's a bare string (any bundle written before edge provenance/
/// confidence existed) or `okf-generator`'s current
/// `{target, resolved_by, confidence}` mapping — mirrors
/// `okf_parser::bundle::parse_relationship_entry`'s own leniency, since
/// this validator re-parses the raw frontmatter YAML independently rather
/// than going through `read_bundle`.
fn relationship_target(value: &serde_yaml::Value) -> Option<&str> {
    value
        .as_str()
        .or_else(|| value.as_mapping()?.get("target")?.as_str())
}

/// A `relationships` target under the `external/` prefix names something
/// outside the bundle by convention (e.g. a third-party import — see
/// `okf-generator`'s external-target handling) and is never expected to
/// resolve to a concept file, so it's exempt from this check.
fn is_external_target(target: &str) -> bool {
    target.starts_with("external/")
}

/// Every `relationships` entry in a concept's frontmatter (`calls`,
/// `called_by`, `imports`, `member_of`, ...) names another concept by id;
/// this checks each one resolves to a real file in the bundle, the same
/// way `check_links_and_collect` does for markdown body links. Without
/// this, a stale or hand-edited relationship target silently vanishes in
/// `okf-graph` (`Graph::get` returns `None` and it's filtered out of
/// results) instead of being reported.
fn check_relationship_targets(
    files: &[ScannedFile],
    known_paths: &HashSet<&str>,
    report: &mut ValidationReport,
) {
    for file in files {
        if is_index(&file.relative) {
            continue;
        }
        let Some((yaml, _)) = split_frontmatter(&file.content) else {
            continue;
        };
        let Ok(value) = serde_yaml::from_str::<serde_yaml::Value>(yaml) else {
            continue;
        };
        let Some(mapping) = value.as_mapping() else {
            continue;
        };
        let Some(relationships) = mapping.get("relationships").and_then(|v| v.as_mapping()) else {
            continue;
        };

        for (kind, targets) in relationships {
            let kind = kind.as_str().unwrap_or("relationships");
            let Some(targets) = targets.as_sequence() else {
                continue;
            };
            for target in targets {
                let Some(target) = relationship_target(target) else {
                    continue;
                };
                if is_external_target(target) {
                    continue;
                }
                let target_path = format!("{target}.md");
                if !known_paths.contains(target_path.as_str()) {
                    report.issues.push(ValidationIssue {
                        severity: Severity::Error,
                        file: file.relative.clone(),
                        message: format!(
                            "`relationships.{kind}` references `{target}`, which doesn't exist in the bundle"
                        ),
                    });
                }
            }
        }
    }
}

/// Validates a `relationships` entry's provenance/confidence metadata,
/// where present — the "provenance-metadata validation" the CI-validation
/// roadmap item names, now that edge provenance/confidence actually
/// exists to validate. A bare-string entry (no metadata at all — any
/// bundle written before this field existed) is always valid; nothing
/// here requires the new shape. Only checks a *populated but wrong*
/// `confidence` (not one of `exact`/`semantic`) or an explicitly *empty*
/// `resolved_by` — a missing field either way already has a sensible
/// default applied on read (`okf_parser::bundle::parse_relationship_entry`),
/// so there's nothing to flag about absence, only about a present value
/// that can't mean anything.
fn check_relationship_provenance(files: &[ScannedFile], report: &mut ValidationReport) {
    for file in files {
        if is_index(&file.relative) {
            continue;
        }
        let Some((yaml, _)) = split_frontmatter(&file.content) else {
            continue;
        };
        let Ok(value) = serde_yaml::from_str::<serde_yaml::Value>(yaml) else {
            continue;
        };
        let Some(mapping) = value.as_mapping() else {
            continue;
        };
        let Some(relationships) = mapping.get("relationships").and_then(|v| v.as_mapping()) else {
            continue;
        };

        for (kind, targets) in relationships {
            let kind = kind.as_str().unwrap_or("relationships");
            let Some(targets) = targets.as_sequence() else {
                continue;
            };
            for entry in targets {
                let Some(entry_map) = entry.as_mapping() else {
                    continue;
                };
                let target = entry_map
                    .get("target")
                    .and_then(|v| v.as_str())
                    .unwrap_or("<unknown target>");
                if let Some(confidence) = entry_map.get("confidence").and_then(|v| v.as_str()) {
                    // Deliberately a local literal list, not
                    // `okf_parser::Confidence`: this validator re-parses
                    // raw frontmatter YAML independently of `okf-parser`
                    // everywhere else (see `relationship_target`'s docs),
                    // so a malformed bundle stays checkable even if it
                    // wouldn't parse via `read_bundle` at all.
                    if !matches!(confidence, "exact" | "semantic") {
                        report.issues.push(ValidationIssue {
                            severity: Severity::Error,
                            file: file.relative.clone(),
                            message: format!(
                                "`relationships.{kind}` entry for `{target}` has an unrecognized `confidence: {confidence}` (expected `exact` or `semantic`)"
                            ),
                        });
                    }
                }
                if entry_map.get("resolved_by").and_then(|v| v.as_str()) == Some("") {
                    report.issues.push(ValidationIssue {
                        severity: Severity::Error,
                        file: file.relative.clone(),
                        message: format!(
                            "`relationships.{kind}` entry for `{target}` has an empty `resolved_by`"
                        ),
                    });
                }
            }
        }
    }
}

/// Bundle-wide `Calls`/`CalledBy` symmetry. `okf-analyzer` always pushes
/// both sides of a resolved call edge together (a `Calls` relationship on
/// the caller, a `CalledBy` relationship on the callee), so an asymmetric
/// pair only arises in a hand-edited or drifted bundle — this is a safety
/// net for that, not something a plain `okf-rs generate` output should
/// ever trigger. No other relationship kind (`Imports`, `Implements`,
/// `Inherits`, `DependsOn`, `MemberOf`) has a reverse kind in
/// `RelationKind` at all, so this check only ever applies to this one
/// pair — checking any other kind for "symmetry" would be meaningless.
///
/// A target that doesn't exist in the bundle at all is already reported
/// by `check_relationship_targets`; re-flagging it here as "asymmetric"
/// too would just be the same problem under a second, more confusing
/// message, so this only considers targets known to exist.
fn check_relationship_symmetry(
    files: &[ScannedFile],
    known_paths: &HashSet<&str>,
    report: &mut ValidationReport,
) {
    let mut calls_of: HashMap<String, HashSet<String>> = HashMap::new();
    let mut called_by_of: HashMap<String, HashSet<String>> = HashMap::new();

    for file in files {
        if is_index(&file.relative) {
            continue;
        }
        let Some((yaml, _)) = split_frontmatter(&file.content) else {
            continue;
        };
        let Ok(value) = serde_yaml::from_str::<serde_yaml::Value>(yaml) else {
            continue;
        };
        let Some(mapping) = value.as_mapping() else {
            continue;
        };
        let Some(relationships) = mapping.get("relationships").and_then(|v| v.as_mapping()) else {
            continue;
        };
        let id = file.relative.strip_suffix(".md").unwrap_or(&file.relative);

        for (bucket, key) in [(&mut calls_of, "calls"), (&mut called_by_of, "called_by")] {
            if let Some(targets) = relationships.get(key).and_then(|v| v.as_sequence()) {
                bucket.entry(id.to_string()).or_default().extend(
                    targets
                        .iter()
                        .filter_map(relationship_target)
                        .map(String::from),
                );
            }
        }
    }

    check_symmetry_direction(
        &calls_of,
        &called_by_of,
        known_paths,
        "calls",
        "called_by",
        report,
    );
    check_symmetry_direction(
        &called_by_of,
        &calls_of,
        known_paths,
        "called_by",
        "calls",
        report,
    );
}

/// One direction of `check_relationship_symmetry`: for every `id -> target`
/// edge in `forward`, requires `reverse` to carry the matching
/// `target -> id` edge back. Called twice (`calls`/`called_by`, then
/// swapped) to cover both directions without duplicating this loop.
fn check_symmetry_direction(
    forward: &HashMap<String, HashSet<String>>,
    reverse: &HashMap<String, HashSet<String>>,
    known_paths: &HashSet<&str>,
    forward_key: &str,
    reverse_key: &str,
    report: &mut ValidationReport,
) {
    for (id, targets) in forward {
        for target in targets {
            if is_external_target(target) {
                continue;
            }
            let target_path = format!("{target}.md");
            if !known_paths.contains(target_path.as_str()) {
                continue;
            }
            let has_reverse = reverse.get(target).is_some_and(|s| s.contains(id));
            if !has_reverse {
                report.issues.push(ValidationIssue {
                    severity: Severity::Warning,
                    file: target_path,
                    message: format!(
                        "`{id}` lists `relationships.{forward_key}: {target}`, but `{target}` doesn't list `relationships.{reverse_key}: {id}` back"
                    ),
                });
            }
        }
    }
}

fn extract_local_links(content: &str) -> Vec<String> {
    // A minimal markdown-link scanner (avoids pulling in a regex/markdown
    // dependency for one pattern): finds `](...)` and keeps the ones that
    // look like relative `.md` links, skipping absolute URLs and anchors.
    let mut links = Vec::new();
    let mut rest = content;
    while let Some(pos) = rest.find("](") {
        let after = &rest[pos + 2..];
        if let Some(end) = after.find(')') {
            let target = &after[..end];
            if target.ends_with(".md") && !target.contains("://") && !target.starts_with('#') {
                links.push(target.to_string());
            }
            rest = &after[end + 1..];
        } else {
            break;
        }
    }
    links
}

/// Resolves `link` relative to the directory containing `from_relative`,
/// normalizing `.`/`..` components. Returns `None` if the link escapes the
/// bundle root.
fn resolve_link(from_relative: &str, link: &str) -> Option<String> {
    let mut components: Vec<&str> = from_relative.split('/').collect();
    components.pop(); // drop the file name, keep its directory
    for part in link.split('/') {
        match part {
            "" | "." => {}
            ".." => {
                components.pop()?;
            }
            other => components.push(other),
        }
    }
    Some(components.join("/"))
}

fn check_links_and_collect(
    files: &[ScannedFile],
    known_paths: &HashSet<&str>,
    report: &mut ValidationReport,
) -> HashMap<String, Vec<String>> {
    let mut graph: HashMap<String, Vec<String>> = HashMap::new();
    for file in files {
        let mut resolved_targets = Vec::new();
        let mut seen_targets: HashSet<String> = HashSet::new();
        for link in extract_local_links(&file.content) {
            match resolve_link(&file.relative, &link) {
                Some(target) if known_paths.contains(target.as_str()) => {
                    if !seen_targets.insert(target.clone()) {
                        report.issues.push(ValidationIssue {
                            severity: Severity::Warning,
                            file: file.relative.clone(),
                            message: format!("redundant link to `{target}` (already linked earlier in this file)"),
                        });
                    }
                    resolved_targets.push(target);
                }
                Some(target) => {
                    report.issues.push(ValidationIssue {
                        severity: Severity::Error,
                        file: file.relative.clone(),
                        message: format!("dangling link to `{target}` (resolved from `{link}`)"),
                    });
                }
                None => {
                    report.issues.push(ValidationIssue {
                        severity: Severity::Error,
                        file: file.relative.clone(),
                        message: format!("link `{link}` escapes the bundle root"),
                    });
                }
            }
        }
        graph.insert(file.relative.clone(), resolved_targets);
    }
    graph
}

fn check_reachability(
    files: &[ScannedFile],
    links: &HashMap<String, Vec<String>>,
    report: &mut ValidationReport,
) {
    let mut visited: HashSet<String> = HashSet::new();
    let mut queue: VecDeque<String> = VecDeque::new();
    if links.contains_key("index.md") {
        queue.push_back("index.md".to_string());
        visited.insert("index.md".to_string());
    }
    while let Some(current) = queue.pop_front() {
        for target in links.get(&current).into_iter().flatten() {
            if visited.insert(target.clone()) {
                queue.push_back(target.clone());
            }
        }
    }

    for file in files {
        if is_index(&file.relative) || visited.contains(&file.relative) {
            continue;
        }
        report.issues.push(ValidationIssue {
            severity: Severity::Warning,
            file: file.relative.clone(),
            message: "not reachable from index.md (orphaned concept)".to_string(),
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write(dir: &Path, relative: &str, content: &str) {
        let path = dir.join(relative);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, content).unwrap();
    }

    #[test]
    fn passes_a_well_formed_bundle() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "index.md",
            "- [Functions](functions/index.md)\n",
        );
        write(dir.path(), "functions/index.md", "- [run](run.md)\n");
        write(
            dir.path(),
            "functions/run.md",
            "---\ntype: Rust Function\ntitle: run\nresource: src/main.rs#L1\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(
            !report.has_errors(),
            "unexpected errors: {:?}",
            report.issues
        );
        assert!(report.issues.is_empty());
    }

    #[test]
    fn flags_missing_type_dangling_link_and_orphan() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "index.md", "no links here\n");
        write(
            dir.path(),
            "functions/run.md",
            "---\ntitle: run\nresource: src/main.rs#L1\n---\n\n[gone](../functions/missing.md)\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(report.has_errors());
        assert!(report
            .issues
            .iter()
            .any(|i| i.message.contains("mandatory non-empty `type`")));
        assert!(report
            .issues
            .iter()
            .any(|i| i.message.contains("dangling link")));
        assert!(report
            .issues
            .iter()
            .any(|i| i.severity == Severity::Warning && i.message.contains("orphaned")));
    }

    #[test]
    fn flags_invalid_tags_and_timestamp() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "index.md", "");
        write(
            dir.path(),
            "functions/run.md",
            "---\ntype: Rust Function\ntags: not-a-list\ntimestamp: not-a-date\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(report.issues.iter().any(|i| i.message.contains("`tags`")));
        assert!(report
            .issues
            .iter()
            .any(|i| i.message.contains("`timestamp`")));
    }

    #[test]
    fn accepts_crlf_frontmatter() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "index.md", "- [run](functions/run.md)\n");
        write(
            dir.path(),
            "functions/run.md",
            "---\r\ntype: Rust Function\r\ntitle: run\r\nresource: src/main.rs#L1\r\n---\r\n\r\nbody\r\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(
            !report.has_errors(),
            "CRLF-formatted frontmatter should still validate cleanly: {:?}",
            report.issues
        );
    }

    #[test]
    fn flags_same_resource_emitted_under_two_different_paths() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "index.md",
            "- [a](functions/verify_token.md)\n- [b](functions/verify_token_v2.md)\n",
        );
        write(
            dir.path(),
            "functions/verify_token.md",
            "---\ntype: Rust Function\ntitle: verify_token\nresource: src/auth/token.rs#L42\n---\n\nbody\n",
        );
        write(
            dir.path(),
            "functions/verify_token_v2.md",
            "---\ntype: Rust Function\ntitle: verify_token\nresource: src/auth/token.rs#L42\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(report.has_errors());
        assert_eq!(
            report
                .issues
                .iter()
                .filter(|i| i.message.contains("duplicate concept identity"))
                .count(),
            2,
            "both files sharing the resource should be flagged: {:?}",
            report.issues
        );
    }

    #[test]
    fn a_module_spanning_its_sole_member_is_not_a_duplicate() {
        // A file containing exactly one top-level item (common for small
        // single-purpose files) makes the Module concept's whole-file
        // `resource` span identical to that lone member's — that's
        // expected containment, not a duplicate identity.
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "index.md",
            "- [mod](modules/auth.md)\n- [fn](functions/auth/verify_token.md)\n",
        );
        write(
            dir.path(),
            "modules/auth.md",
            "---\ntype: Rust Module\ntitle: auth\nresource: src/auth.rs#L1-L3\n---\n\nbody\n",
        );
        write(
            dir.path(),
            "functions/auth/verify_token.md",
            "---\ntype: Rust Function\ntitle: verify_token\nresource: src/auth.rs#L1-L3\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(
            !report.has_errors(),
            "Module-vs-sole-member overlap should not be flagged: {:?}",
            report.issues
        );
    }

    #[test]
    fn two_modules_sharing_a_resource_is_still_a_duplicate() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "index.md",
            "- [a](modules/a.md)\n- [b](modules/b.md)\n",
        );
        write(
            dir.path(),
            "modules/a.md",
            "---\ntype: Rust Module\ntitle: a\nresource: src/lib.rs#L1-L3\n---\n\nbody\n",
        );
        write(
            dir.path(),
            "modules/b.md",
            "---\ntype: Rust Module\ntitle: b\nresource: src/lib.rs#L1-L3\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(report.has_errors());
        assert_eq!(
            report
                .issues
                .iter()
                .filter(|i| i.message.contains("duplicate concept identity"))
                .count(),
            2,
            "two Module concepts sharing a resource should still be flagged: {:?}",
            report.issues
        );
    }

    #[test]
    fn flags_a_missing_root_index() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "functions/run.md",
            "---\ntype: Rust Function\ntitle: run\nresource: src/main.rs#L1\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(report.has_errors());
        assert!(report
            .issues
            .iter()
            .any(|i| i.message.contains("missing required root `index.md`")));
    }

    #[test]
    fn flags_a_relationship_target_that_does_not_exist() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "index.md", "- [run](functions/run.md)\n");
        write(
            dir.path(),
            "functions/run.md",
            "---\ntype: Rust Function\ntitle: run\nresource: src/main.rs#L1\nrelationships:\n  calls:\n    - functions/missing\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(report.has_errors());
        assert!(report.issues.iter().any(|i| {
            i.message.contains("relationships.calls") && i.message.contains("functions/missing")
        }));
    }

    #[test]
    fn accepts_an_external_relationship_target() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "index.md", "- [run](functions/run.md)\n");
        write(
            dir.path(),
            "functions/run.md",
            "---\ntype: Rust Module\ntitle: run\nresource: src/main.rs#L1\nrelationships:\n  imports:\n    - external/std-collections-hashmap\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(
            !report.has_errors(),
            "an external:// relationship target should not be flagged: {:?}",
            report.issues
        );
    }

    #[test]
    fn accepts_the_object_shaped_relationship_entry_with_valid_provenance() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "index.md", "- [run](functions/run.md)\n");
        write(
            dir.path(),
            "functions/callee.md",
            "---\ntype: Rust Function\ntitle: callee\nresource: src/main.rs#L1\n---\n\nbody\n",
        );
        write(
            dir.path(),
            "functions/run.md",
            "---\ntype: Rust Function\ntitle: run\nresource: src/main.rs#L5\nrelationships:\n  calls:\n    - target: functions/callee\n      resolved_by: rust-analyzer\n      confidence: semantic\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(
            !report.has_errors(),
            "a valid object-shaped relationship entry should not be flagged: {:?}",
            report.issues
        );
    }

    #[test]
    fn flags_an_unrecognized_confidence_value() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "index.md", "- [run](functions/run.md)\n");
        write(
            dir.path(),
            "functions/callee.md",
            "---\ntype: Rust Function\ntitle: callee\nresource: src/main.rs#L1\n---\n\nbody\n",
        );
        write(
            dir.path(),
            "functions/run.md",
            "---\ntype: Rust Function\ntitle: run\nresource: src/main.rs#L5\nrelationships:\n  calls:\n    - target: functions/callee\n      confidence: probably\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(report.has_errors());
        assert!(report.issues.iter().any(|i| {
            i.message.contains("unrecognized `confidence: probably`")
                && i.message.contains("functions/callee")
        }));
    }

    #[test]
    fn flags_an_empty_resolved_by() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "index.md", "- [run](functions/run.md)\n");
        write(
            dir.path(),
            "functions/callee.md",
            "---\ntype: Rust Function\ntitle: callee\nresource: src/main.rs#L1\n---\n\nbody\n",
        );
        write(
            dir.path(),
            "functions/run.md",
            "---\ntype: Rust Function\ntitle: run\nresource: src/main.rs#L5\nrelationships:\n  calls:\n    - target: functions/callee\n      resolved_by: \"\"\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(report.has_errors());
        assert!(report
            .issues
            .iter()
            .any(|i| i.message.contains("empty `resolved_by`")));
    }

    #[test]
    fn a_bare_string_relationship_entry_has_no_provenance_to_flag() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "index.md", "- [run](functions/run.md)\n");
        write(
            dir.path(),
            "functions/callee.md",
            "---\ntype: Rust Function\ntitle: callee\nresource: src/main.rs#L1\n---\n\nbody\n",
        );
        write(
            dir.path(),
            "functions/run.md",
            "---\ntype: Rust Function\ntitle: run\nresource: src/main.rs#L5\nrelationships:\n  calls:\n    - functions/callee\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(
            !report.has_errors(),
            "a bare-string relationship entry (pre-provenance bundle format) should stay valid: {:?}",
            report.issues
        );
    }

    #[test]
    fn flags_a_redundant_duplicate_link() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "index.md",
            "- [run](functions/run.md)\n- [run again](functions/run.md)\n",
        );
        write(
            dir.path(),
            "functions/run.md",
            "---\ntype: Rust Function\ntitle: run\nresource: src/main.rs#L1\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(
            !report.has_errors(),
            "a redundant link is a warning, not an error: {:?}",
            report.issues
        );
        assert!(report
            .issues
            .iter()
            .any(|i| { i.severity == Severity::Warning && i.message.contains("redundant link") }));
    }

    #[test]
    fn accepts_symmetric_calls_and_called_by() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "index.md",
            "- [a](functions/a.md)\n- [b](functions/b.md)\n",
        );
        write(
            dir.path(),
            "functions/a.md",
            "---\ntype: Rust Function\ntitle: a\nresource: src/lib.rs#L1\nrelationships:\n  calls:\n    - functions/b\n---\n\nbody\n",
        );
        write(
            dir.path(),
            "functions/b.md",
            "---\ntype: Rust Function\ntitle: b\nresource: src/lib.rs#L2\nrelationships:\n  called_by:\n    - functions/a\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(
            !report.has_errors(),
            "unexpected errors: {:?}",
            report.issues
        );
        assert!(
            !report
                .issues
                .iter()
                .any(|i| i.message.contains("doesn't list")),
            "a symmetric Calls/CalledBy pair should not be flagged: {:?}",
            report.issues
        );
    }

    #[test]
    fn flags_a_calls_edge_with_no_reciprocal_called_by() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "index.md",
            "- [a](functions/a.md)\n- [b](functions/b.md)\n",
        );
        write(
            dir.path(),
            "functions/a.md",
            "---\ntype: Rust Function\ntitle: a\nresource: src/lib.rs#L1\nrelationships:\n  calls:\n    - functions/b\n---\n\nbody\n",
        );
        write(
            dir.path(),
            "functions/b.md",
            "---\ntype: Rust Function\ntitle: b\nresource: src/lib.rs#L2\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(
            !report.has_errors(),
            "asymmetry is a warning, not an error: {:?}",
            report.issues
        );
        assert!(report.issues.iter().any(|i| {
            i.severity == Severity::Warning
                && i.file == "functions/b.md"
                && i.message.contains("relationships.calls: functions/b")
                && i.message.contains("relationships.called_by: functions/a")
        }));
    }

    #[test]
    fn asymmetric_external_call_is_not_flagged() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "index.md", "- [a](functions/a.md)\n");
        write(
            dir.path(),
            "functions/a.md",
            "---\ntype: Rust Function\ntitle: a\nresource: src/lib.rs#L1\nrelationships:\n  calls:\n    - external/std-mem-swap\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(
            !report
                .issues
                .iter()
                .any(|i| i.message.contains("doesn't list")),
            "an external call target has no reciprocal side to check: {:?}",
            report.issues
        );
    }

    #[test]
    fn accepts_a_fully_populated_v0_2_trust_bundle() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "index.md",
            "---\nokf_version: \"0.2\"\n---\n\n- [run](functions/run.md)\n",
        );
        write(
            dir.path(),
            "functions/run.md",
            "---\n\
             type: Rust Function\n\
             title: run\n\
             resource: src/main.rs#L1\n\
             status: stable\n\
             stale_after: 2027-01-01\n\
             generated: { by: okf-rs/0.1.0, at: 2026-07-30T00:00:00Z }\n\
             verified: { by: human:ahormati, at: 2026-07-30T00:00:00Z }\n\
             sources:\n  \
               - resource: https://example.com/spec\n    \
                 last_modified: 2026-01-01\n    \
                 usage_count: 5\n\
             usage_window: { from: 2026-01-01, to: 2026-02-01 }\n\
             ---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(
            !report.has_errors(),
            "unexpected errors: {:?}",
            report.issues
        );
    }

    #[test]
    fn flags_malformed_trust_and_lifecycle_fields() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "index.md", "- [run](functions/run.md)\n");
        write(
            dir.path(),
            "functions/run.md",
            "---\n\
             type: Rust Function\n\
             title: run\n\
             resource: src/main.rs#L1\n\
             status: nope\n\
             stale_after: not-a-date\n\
             generated: { at: 2026-07-30T00:00:00Z }\n\
             verified:\n  - { by: '', at: 2026-07-30T00:00:00Z }\n\
             sources:\n  - { title: no-resource }\n\
             ---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(report.has_errors());
        let messages: Vec<&str> = report.issues.iter().map(|i| i.message.as_str()).collect();
        assert!(messages.iter().any(|m| m.contains("`status`")));
        assert!(messages.iter().any(|m| m.contains("`stale_after`")));
        assert!(messages
            .iter()
            .any(|m| m.contains("`generated` is missing")));
        assert!(messages
            .iter()
            .any(|m| m.contains("`verified` entry is missing")));
        assert!(messages
            .iter()
            .any(|m| m.contains("`sources` entry is missing")));
    }

    #[test]
    fn warns_on_actor_not_following_convention() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "index.md", "- [run](functions/run.md)\n");
        write(
            dir.path(),
            "functions/run.md",
            "---\ntype: Rust Function\ntitle: run\nresource: src/main.rs#L1\ngenerated: { by: some-random-name }\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(!report.has_errors());
        assert!(report
            .issues
            .iter()
            .any(|i| i.severity == Severity::Warning && i.message.contains("actor convention")));
    }

    #[test]
    fn attested_computation_requires_runtime() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "index.md", "- [rev](computations/rev.md)\n");
        write(
            dir.path(),
            "computations/rev.md",
            "---\ntype: Attested Computation\ntitle: Revenue\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(report.has_errors());
        assert!(report
            .issues
            .iter()
            .any(|i| i.message.contains("requires a non-empty `runtime`")));
    }

    #[test]
    fn rejects_malformed_root_okf_version() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "index.md",
            "---\nokf_version: not-a-version\n---\n\n- [run](functions/run.md)\n",
        );
        write(
            dir.path(),
            "functions/run.md",
            "---\ntype: Rust Function\ntitle: run\nresource: src/main.rs#L1\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(report
            .issues
            .iter()
            .any(|i| i.message.contains("`okf_version` must be")));
    }

    #[test]
    fn accepts_unquoted_numeric_okf_version() {
        // YAML parses a bare `okf_version: 0.2` as a numeric scalar, not a
        // string; this is still a semantically valid version declaration
        // and must not be rejected.
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "index.md",
            "---\nokf_version: 0.2\n---\n\n- [run](functions/run.md)\n",
        );
        write(
            dir.path(),
            "functions/run.md",
            "---\ntype: Rust Function\ntitle: run\nresource: src/main.rs#L1\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(
            !report.has_errors(),
            "unquoted okf_version should validate cleanly: {:?}",
            report.issues
        );
    }

    #[test]
    fn rejects_frontmatter_on_non_root_index() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "index.md", "- [fns](functions/index.md)\n");
        write(
            dir.path(),
            "functions/index.md",
            "---\nokf_version: \"0.2\"\n---\n\n- [run](run.md)\n",
        );
        write(
            dir.path(),
            "functions/run.md",
            "---\ntype: Rust Function\ntitle: run\nresource: src/main.rs#L1\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(report.issues.iter().any(|i| i.file == "functions/index.md"
            && i.message.contains("only the bundle-root index.md")));
    }
}
