//! Validates that a directory is a conformant OKF bundle — generated by
//! `okf-generator` or hand-edited — per the checks described in the
//! project specification's Validation section:
//!
//! - every concept file has a valid YAML frontmatter block with the
//!   mandatory `type` field
//! - frontmatter values match expected shapes (`tags` is a list,
//!   `timestamp` is RFC 3339)
//! - markdown links between concepts resolve to files that exist in the
//!   bundle (no dangling references)
//! - every concept is reachable from an `index.md` (no orphaned files)
//! - no duplicate concept identity: neither two files colliding on path
//!   (case-insensitively, since paths become filesystem entries that may
//!   not distinguish case) nor two files independently describing the
//!   same source location (`resource`)
//!
//! Schema-version conformance (the sixth check named in the spec) is not
//! implemented yet: okf-rs doesn't emit a schema version into bundles in
//! Phase 1, so there is nothing yet to check it against.

use anyhow::{Context, Result};
use std::collections::{HashMap, HashSet, VecDeque};
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Severity {
    Error,
    Warning,
}

#[derive(Debug, Clone)]
pub struct ValidationIssue {
    pub severity: Severity,
    /// Path relative to the bundle root.
    pub file: String,
    pub message: String,
}

#[derive(Debug, Default)]
pub struct ValidationReport {
    pub issues: Vec<ValidationIssue>,
}

impl ValidationReport {
    pub fn has_errors(&self) -> bool {
        self.issues.iter().any(|i| i.severity == Severity::Error)
    }
}

struct ScannedFile {
    /// Relative path, `/`-separated, including `.md`.
    relative: String,
    content: String,
}

/// Walks `bundle_dir` and runs every validation check against it.
pub fn validate_bundle(bundle_dir: &Path) -> Result<ValidationReport> {
    let mut files = Vec::new();
    for entry in walkdir::WalkDir::new(bundle_dir) {
        let entry = entry.context("failed to walk bundle directory")?;
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("md") {
            continue;
        }
        let relative = path
            .strip_prefix(bundle_dir)
            .unwrap_or(path)
            .to_string_lossy()
            .replace('\\', "/");
        // Normalize CRLF to LF before any frontmatter parsing: files
        // edited or checked out on Windows (or with `core.autocrlf=true`)
        // are otherwise valid OKF content that the `"---\n"` delimiter
        // match would reject wholesale as "missing frontmatter".
        let content = fs::read_to_string(path)
            .with_context(|| format!("failed to read {relative}"))?
            .replace("\r\n", "\n");
        files.push(ScannedFile { relative, content });
    }
    files.sort_by(|a, b| a.relative.cmp(&b.relative));

    let mut report = ValidationReport::default();
    let known_paths: HashSet<&str> = files.iter().map(|f| f.relative.as_str()).collect();

    check_frontmatter(&files, &mut report);
    check_duplicate_ids(&files, &mut report);
    check_duplicate_resources(&files, &mut report);
    let links = check_links_and_collect(&files, &known_paths, &mut report);
    check_reachability(&files, &links, &mut report);

    Ok(report)
}

fn is_index(relative: &str) -> bool {
    relative == "index.md" || relative.ends_with("/index.md")
}

fn split_frontmatter(content: &str) -> Option<(&str, &str)> {
    let rest = content.strip_prefix("---\n")?;
    let end = rest.find("\n---\n")?;
    Some((&rest[..end], &rest[end + 5..]))
}

fn check_frontmatter(files: &[ScannedFile], report: &mut ValidationReport) {
    for file in files {
        if is_index(&file.relative) {
            continue;
        }
        let Some((yaml, _body)) = split_frontmatter(&file.content) else {
            report.issues.push(ValidationIssue {
                severity: Severity::Error,
                file: file.relative.clone(),
                message: "missing or malformed YAML frontmatter (expected a `---` delimited block)"
                    .to_string(),
            });
            continue;
        };

        let value: serde_yaml::Value = match serde_yaml::from_str(yaml) {
            Ok(v) => v,
            Err(e) => {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: file.relative.clone(),
                    message: format!("invalid YAML frontmatter: {e}"),
                });
                continue;
            }
        };

        let Some(mapping) = value.as_mapping() else {
            report.issues.push(ValidationIssue {
                severity: Severity::Error,
                file: file.relative.clone(),
                message: "frontmatter must be a YAML mapping".to_string(),
            });
            continue;
        };

        match mapping.get("type").and_then(|v| v.as_str()) {
            Some(t) if !t.trim().is_empty() => {}
            _ => report.issues.push(ValidationIssue {
                severity: Severity::Error,
                file: file.relative.clone(),
                message: "frontmatter is missing the mandatory non-empty `type` field".to_string(),
            }),
        }

        if let Some(tags) = mapping.get("tags") {
            let valid = tags
                .as_sequence()
                .map(|seq| seq.iter().all(|t| t.as_str().is_some()))
                .unwrap_or(false);
            if !valid {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: file.relative.clone(),
                    message: "`tags` must be a list of strings".to_string(),
                });
            }
        }

        if let Some(timestamp) = mapping.get("timestamp") {
            let raw = timestamp.as_str().map(str::to_string).or_else(|| {
                // serde_yaml may parse an unquoted RFC 3339 value as its own
                // timestamp-like scalar; round-trip it back to a string.
                serde_yaml::to_string(timestamp)
                    .ok()
                    .map(|s| s.trim().to_string())
            });
            let parses = raw
                .as_deref()
                .map(|s| chrono::DateTime::parse_from_rfc3339(s).is_ok())
                .unwrap_or(false);
            if !parses {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: file.relative.clone(),
                    message: "`timestamp` must be an RFC 3339 datetime".to_string(),
                });
            }
        }
    }
}

fn check_duplicate_ids(files: &[ScannedFile], report: &mut ValidationReport) {
    let mut by_lower: HashMap<String, Vec<&str>> = HashMap::new();
    for file in files {
        by_lower
            .entry(file.relative.to_ascii_lowercase())
            .or_default()
            .push(&file.relative);
    }
    for (_, paths) in by_lower {
        if paths.len() > 1 {
            let mut sorted = paths.clone();
            sorted.sort();
            for path in &sorted {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: path.to_string(),
                    message: format!(
                        "concept id collides case-insensitively with: {}",
                        sorted
                            .iter()
                            .filter(|p| **p != *path)
                            .cloned()
                            .collect::<Vec<_>>()
                            .join(", ")
                    ),
                });
            }
        }
    }
}

/// Catches the OKF spec's other "duplicate concept identity" case:
/// `check_duplicate_ids` only catches two files that collide on *path*,
/// but a source symbol can just as easily be emitted twice under two
/// *different* paths (e.g. a stale file left behind after a rename, or a
/// hand-edited copy) — that's detected here by two concept files sharing
/// the same `resource` (source location).
///
/// A `Module` concept's `resource` is definitionally the whole file, so it
/// legitimately coincides with a member's location whenever that member is
/// the file's only top-level item (a common shape: a file containing
/// exactly one function/class/struct) — that's expected containment, not
/// a duplicate identity. So `Module` resources and non-`Module` resources
/// are checked for collisions separately: a real duplicate (two `Function`
/// files sharing a resource, or two `Module` files sharing one) is still
/// caught, but a `Module` overlapping its own sole member never is.
fn check_duplicate_resources(files: &[ScannedFile], report: &mut ValidationReport) {
    let mut by_resource: HashMap<String, Vec<(&str, bool)>> = HashMap::new();
    for file in files {
        if is_index(&file.relative) {
            continue;
        }
        let Some((yaml, _)) = split_frontmatter(&file.content) else {
            continue;
        };
        let Ok(value) = serde_yaml::from_str::<serde_yaml::Value>(yaml) else {
            continue;
        };
        let Some(mapping) = value.as_mapping() else {
            continue;
        };
        let Some(resource) = mapping.get("resource").and_then(|v| v.as_str()) else {
            continue;
        };
        let is_module = mapping
            .get("type")
            .and_then(|v| v.as_str())
            .is_some_and(|t| t.ends_with(" Module"));
        by_resource
            .entry(resource.to_string())
            .or_default()
            .push((&file.relative, is_module));
    }

    for (resource, entries) in by_resource {
        let modules: Vec<&str> = entries
            .iter()
            .filter(|(_, is_module)| *is_module)
            .map(|(path, _)| *path)
            .collect();
        let others: Vec<&str> = entries
            .iter()
            .filter(|(_, is_module)| !*is_module)
            .map(|(path, _)| *path)
            .collect();

        for paths in [modules, others] {
            if paths.len() <= 1 {
                continue;
            }
            let mut sorted = paths.clone();
            sorted.sort();
            for path in &sorted {
                report.issues.push(ValidationIssue {
                    severity: Severity::Error,
                    file: path.to_string(),
                    message: format!(
                        "duplicate concept identity: `resource: {resource}` also appears in: {}",
                        sorted
                            .iter()
                            .filter(|p| **p != *path)
                            .cloned()
                            .collect::<Vec<_>>()
                            .join(", ")
                    ),
                });
            }
        }
    }
}

fn extract_local_links(content: &str) -> Vec<String> {
    // A minimal markdown-link scanner (avoids pulling in a regex/markdown
    // dependency for one pattern): finds `](...)` and keeps the ones that
    // look like relative `.md` links, skipping absolute URLs and anchors.
    let mut links = Vec::new();
    let mut rest = content;
    while let Some(pos) = rest.find("](") {
        let after = &rest[pos + 2..];
        if let Some(end) = after.find(')') {
            let target = &after[..end];
            if target.ends_with(".md") && !target.contains("://") && !target.starts_with('#') {
                links.push(target.to_string());
            }
            rest = &after[end + 1..];
        } else {
            break;
        }
    }
    links
}

/// Resolves `link` relative to the directory containing `from_relative`,
/// normalizing `.`/`..` components. Returns `None` if the link escapes the
/// bundle root.
fn resolve_link(from_relative: &str, link: &str) -> Option<String> {
    let mut components: Vec<&str> = from_relative.split('/').collect();
    components.pop(); // drop the file name, keep its directory
    for part in link.split('/') {
        match part {
            "" | "." => {}
            ".." => {
                components.pop()?;
            }
            other => components.push(other),
        }
    }
    Some(components.join("/"))
}

fn check_links_and_collect(
    files: &[ScannedFile],
    known_paths: &HashSet<&str>,
    report: &mut ValidationReport,
) -> HashMap<String, Vec<String>> {
    let mut graph: HashMap<String, Vec<String>> = HashMap::new();
    for file in files {
        let mut resolved_targets = Vec::new();
        for link in extract_local_links(&file.content) {
            match resolve_link(&file.relative, &link) {
                Some(target) if known_paths.contains(target.as_str()) => {
                    resolved_targets.push(target);
                }
                Some(target) => {
                    report.issues.push(ValidationIssue {
                        severity: Severity::Error,
                        file: file.relative.clone(),
                        message: format!("dangling link to `{target}` (resolved from `{link}`)"),
                    });
                }
                None => {
                    report.issues.push(ValidationIssue {
                        severity: Severity::Error,
                        file: file.relative.clone(),
                        message: format!("link `{link}` escapes the bundle root"),
                    });
                }
            }
        }
        graph.insert(file.relative.clone(), resolved_targets);
    }
    graph
}

fn check_reachability(
    files: &[ScannedFile],
    links: &HashMap<String, Vec<String>>,
    report: &mut ValidationReport,
) {
    let mut visited: HashSet<String> = HashSet::new();
    let mut queue: VecDeque<String> = VecDeque::new();
    if links.contains_key("index.md") {
        queue.push_back("index.md".to_string());
        visited.insert("index.md".to_string());
    }
    while let Some(current) = queue.pop_front() {
        for target in links.get(&current).into_iter().flatten() {
            if visited.insert(target.clone()) {
                queue.push_back(target.clone());
            }
        }
    }

    for file in files {
        if is_index(&file.relative) || visited.contains(&file.relative) {
            continue;
        }
        report.issues.push(ValidationIssue {
            severity: Severity::Warning,
            file: file.relative.clone(),
            message: "not reachable from index.md (orphaned concept)".to_string(),
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write(dir: &Path, relative: &str, content: &str) {
        let path = dir.join(relative);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, content).unwrap();
    }

    #[test]
    fn passes_a_well_formed_bundle() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "index.md",
            "- [Functions](functions/index.md)\n",
        );
        write(dir.path(), "functions/index.md", "- [run](run.md)\n");
        write(
            dir.path(),
            "functions/run.md",
            "---\ntype: Rust Function\ntitle: run\nresource: src/main.rs#L1\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(
            !report.has_errors(),
            "unexpected errors: {:?}",
            report.issues
        );
        assert!(report.issues.is_empty());
    }

    #[test]
    fn flags_missing_type_dangling_link_and_orphan() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "index.md", "no links here\n");
        write(
            dir.path(),
            "functions/run.md",
            "---\ntitle: run\nresource: src/main.rs#L1\n---\n\n[gone](../functions/missing.md)\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(report.has_errors());
        assert!(report
            .issues
            .iter()
            .any(|i| i.message.contains("mandatory non-empty `type`")));
        assert!(report
            .issues
            .iter()
            .any(|i| i.message.contains("dangling link")));
        assert!(report
            .issues
            .iter()
            .any(|i| i.severity == Severity::Warning && i.message.contains("orphaned")));
    }

    #[test]
    fn flags_invalid_tags_and_timestamp() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "index.md", "");
        write(
            dir.path(),
            "functions/run.md",
            "---\ntype: Rust Function\ntags: not-a-list\ntimestamp: not-a-date\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(report.issues.iter().any(|i| i.message.contains("`tags`")));
        assert!(report
            .issues
            .iter()
            .any(|i| i.message.contains("`timestamp`")));
    }

    #[test]
    fn accepts_crlf_frontmatter() {
        let dir = tempfile::tempdir().unwrap();
        write(dir.path(), "index.md", "- [run](functions/run.md)\n");
        write(
            dir.path(),
            "functions/run.md",
            "---\r\ntype: Rust Function\r\ntitle: run\r\nresource: src/main.rs#L1\r\n---\r\n\r\nbody\r\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(
            !report.has_errors(),
            "CRLF-formatted frontmatter should still validate cleanly: {:?}",
            report.issues
        );
    }

    #[test]
    fn flags_same_resource_emitted_under_two_different_paths() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "index.md",
            "- [a](functions/verify_token.md)\n- [b](functions/verify_token_v2.md)\n",
        );
        write(
            dir.path(),
            "functions/verify_token.md",
            "---\ntype: Rust Function\ntitle: verify_token\nresource: src/auth/token.rs#L42\n---\n\nbody\n",
        );
        write(
            dir.path(),
            "functions/verify_token_v2.md",
            "---\ntype: Rust Function\ntitle: verify_token\nresource: src/auth/token.rs#L42\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(report.has_errors());
        assert_eq!(
            report
                .issues
                .iter()
                .filter(|i| i.message.contains("duplicate concept identity"))
                .count(),
            2,
            "both files sharing the resource should be flagged: {:?}",
            report.issues
        );
    }

    #[test]
    fn a_module_spanning_its_sole_member_is_not_a_duplicate() {
        // A file containing exactly one top-level item (common for small
        // single-purpose files) makes the Module concept's whole-file
        // `resource` span identical to that lone member's — that's
        // expected containment, not a duplicate identity.
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "index.md",
            "- [mod](modules/auth.md)\n- [fn](functions/auth/verify_token.md)\n",
        );
        write(
            dir.path(),
            "modules/auth.md",
            "---\ntype: Rust Module\ntitle: auth\nresource: src/auth.rs#L1-L3\n---\n\nbody\n",
        );
        write(
            dir.path(),
            "functions/auth/verify_token.md",
            "---\ntype: Rust Function\ntitle: verify_token\nresource: src/auth.rs#L1-L3\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(
            !report.has_errors(),
            "Module-vs-sole-member overlap should not be flagged: {:?}",
            report.issues
        );
    }

    #[test]
    fn two_modules_sharing_a_resource_is_still_a_duplicate() {
        let dir = tempfile::tempdir().unwrap();
        write(
            dir.path(),
            "index.md",
            "- [a](modules/a.md)\n- [b](modules/b.md)\n",
        );
        write(
            dir.path(),
            "modules/a.md",
            "---\ntype: Rust Module\ntitle: a\nresource: src/lib.rs#L1-L3\n---\n\nbody\n",
        );
        write(
            dir.path(),
            "modules/b.md",
            "---\ntype: Rust Module\ntitle: b\nresource: src/lib.rs#L1-L3\n---\n\nbody\n",
        );

        let report = validate_bundle(dir.path()).unwrap();
        assert!(report.has_errors());
        assert_eq!(
            report
                .issues
                .iter()
                .filter(|i| i.message.contains("duplicate concept identity"))
                .count(),
            2,
            "two Module concepts sharing a resource should still be flagged: {:?}",
            report.issues
        );
    }
}
